### ISSUE TITLE
[bug] Array index of tmp pass the end of array

### ISSUE THREAD

**Issue by clingfei** [kste/skinny_avx#1]
In `skinny64/avx2/skinny64.c`, there is a definition of tmp:
>  `u256 rc, tmp[3];`

but in the line 71 and line 83, there is `tmp[3] = x[15];` and ` x[3] = XOR(tmp[3], x[15]);`，which pass the end of array tmp[3].

I think define `tmp` as `u256 tmp[4]` is right.

**Comment by kste** [comment]
Thank you for reporting this. I pushed a fix.
